### ISSUE TITLE
材料追加した際に落ちた

### ISSUE THREAD

**Issue by SEKI-YUTA** [SEKI-YUTA/CocktailMaster_JetpackCompose#86]
```
FATAL EXCEPTION: main
                                                                                                    Process: com.yuta.cocktailmaster.physical, PID: 26022
                                                                                                    java.lang.IllegalStateException: replace() called on item that was not placed
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$LookaheadPassDelegate.replace(LayoutNodeLayoutDelegate.kt:1569)
                                                                                                    	at androidx.compose.ui.node.LayoutNode.lookaheadReplace$ui_release(LayoutNode.kt:923)
                                                                                                    	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:486)
                                                                                                    	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded$default(MeasureAndLayoutDelegate.kt:461)
                                                                                                    	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:354)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(AndroidComposeView.android.kt:969)
                                                                                                    	at androidx.compose.ui.node.Owner.measureAndLayout$default(Owner.kt:230)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1222)
                                                                                                    	at android.view.View.draw(View.java:23903)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22767)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4543)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4516)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22723)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4543)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4516)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22723)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4543)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4516)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22723)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4543)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4516)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22723)
                                                                                                    	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
                                                                                                    	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
                                                                                                    	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
                                                                                                    	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5144)
                                                                                                    	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4835)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4011)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2650)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9526)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:882)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8194)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by SEKI-YUTA** [comment]
このエラーはLazyColumnをスクロールした際にも出ていてcomposeBomを更新すれば治った。
そして、材料追加したタイミングで際レンダリングが走るのでその際にエラーが出て落ちていたと思われるので一旦Close
